/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/case-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case File */
        post: operations["create_case_file_case_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case File */
        get: operations["get_case_file_case_files__session_id__get"];
        /** Update Case File */
        put: operations["update_case_file_case_files__session_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Case File */
        post: operations["classify_case_file_case_files__session_id__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_case_files__session_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Returns the opening question (product scope B.5, Node 0/1) without
         *     consuming a user message - call this once right after creating a case
         *     file to get the first prompt to show the user.
         */
        post: operations["start_case_files__session_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_case_files__session_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Product scope §B.7 - runs the tiered OCR/vision pipeline on an
         *     uploaded PDF/PNG/JPEG, extracts whatever Case File facts it can, and
         *     merges them in as document-sourced (never higher-confidence than a
         *     user's own chat answer - see app/ingest/apply.py). Every field this
         *     finds still needs the same B.5 Node 8 confirmation as any other
         *     document-sourced fact before a report is generated - this endpoint pre-
         *     fills, it never finalizes.
         */
        post: operations["upload_document_case_files__session_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_case_files__session_id__documents_post */
        Body_upload_document_case_files__session_id__documents_post: {
            /** File */
            file: string;
        };
        /** CaseFile */
        CaseFile: {
            /** Session Id */
            session_id: string;
            /**
             * Project Name
             * @default
             */
            project_name: string;
            /**
             * State
             * @default
             */
            state: string;
            /**
             * City
             * @default
             */
            city: string;
            occupancy_type?: components["schemas"]["OccupancyType"] | null;
            /**
             * Occupancy Subdivision
             * @description NBCS subdivision code where Table 7's bands genuinely differ by subdivision (e.g. 'A-I' lodging house vs 'A-V' starred hotel within Residential; 'C-I' hospitals vs 'C-II_C-III' custodial/penal within Institutional; 'E-I'/'E-II' human-occupied vs datacentre within Business; 'F'/'F-II' vs underground shopping within Mercantile). NOT part of the original B.4 schema in the product scope document - added because the classifier cannot safely pick a Table 7 band without it for these occupancies. Industrial does not need this field; use industrial_hazard_band.
             */
            occupancy_subdivision?: string | null;
            industrial_hazard_band?: components["schemas"]["IndustrialHazardBand"] | null;
            /**
             * Mixed Occupancy
             * @default false
             */
            mixed_occupancy: boolean;
            /** Occupancy Breakdown */
            occupancy_breakdown?: components["schemas"]["OccupancyBreakdownItem"][];
            /** Height M */
            height_m?: number | null;
            /** Is High Rise */
            is_high_rise?: boolean | null;
            /** Floors Above Ground */
            floors_above_ground?: number | null;
            /** Floors Below Ground */
            floors_below_ground?: number | null;
            /** Built Up Area Sqm */
            built_up_area_sqm?: number | null;
            /** Floor Wise Area */
            floor_wise_area?: components["schemas"]["FloorAreaItem"][];
            /** Number Of Staircases */
            number_of_staircases?: number | null;
            /** Number Of Exits */
            number_of_exits?: number | null;
            /** Existing Fire Systems */
            existing_fire_systems?: string[];
            /**
             * Kitchen Count
             * @description Additions beyond the original B.4 schema, alongside door_count. Report-facing/informational only, same as floor_wise_area - no digitized NBCS Table 7 lookup currently keys off kitchen presence or door count, so these never feed classify().
             */
            kitchen_count?: number | null;
            /** Door Count */
            door_count?: number | null;
            project_stage?: components["schemas"]["ProjectStage"] | null;
            goal?: components["schemas"]["Goal"] | null;
            /**
             * @description Which code edition governs this case. Defaults to 2026 (the live/primary source) unless the case involves a building certified under 2016 and not yet reassessed.
             * @default 2026
             */
            code_edition: components["schemas"]["CodeEdition"];
            /** Source Documents */
            source_documents?: components["schemas"]["SourceDocument"][];
            /** Field Sources */
            field_sources?: {
                [key: string]: components["schemas"]["FieldSource"];
            };
            classification_result?: components["schemas"]["ClassificationResult"];
            /** @default intake */
            conversation_stage: components["schemas"]["ConversationStage"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** ClassificationResult */
        ClassificationResult: {
            /** Applies */
            applies?: boolean | null;
            /**
             * Table 7 Ref
             * @default
             */
            table_7_ref: string;
            /** Applicable Clauses */
            applicable_clauses?: string[];
            /** Applicable State Checklist Id */
            applicable_state_checklist_id?: string | null;
            /** Is High Rise */
            is_high_rise?: boolean | null;
            /**
             * Require Human Review Flag
             * @default false
             */
            require_human_review_flag: boolean;
            /**
             * Protection Level
             * @description e.g. 'HL-3' or 'CL-4' from Table 7A-7J
             */
            protection_level?: string | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * CodeEdition
         * @enum {string}
         */
        CodeEdition: "2026" | "2016";
        /**
         * ConversationStage
         * @enum {string}
         */
        ConversationStage: "intake" | "confirming" | "classified" | "report_ready";
        /** FieldSource */
        FieldSource: {
            /** Value */
            value?: unknown;
            /** @default unknown */
            source: components["schemas"]["FieldSourceKind"];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /**
         * FieldSourceKind
         * @enum {string}
         */
        FieldSourceKind: "user" | "document" | "inferred" | "unknown";
        /**
         * FloorAreaItem
         * @description One row of a floor-wise area breakdown - an addition beyond the
         *     original B.4 schema (which only has a single built_up_area_sqm total).
         *     Added because architectural drawings' "area statement" schedules give
         *     area per floor, not just a building total, and that's useful to capture
         *     even though today's digitized NBCS Table 7 lookups still key off the
         *     single built_up_area_sqm total (see classifier.py) - this is
         *     informational/report-facing only, not a classification input, per an
         *     explicit product decision to not invent NBCS clause logic that doesn't
         *     exist in the digitized rule data.
         */
        FloorAreaItem: {
            /** Floor */
            floor: string;
            /** Area Sqm */
            area_sqm: number;
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "understand_requirements" | "prep_noc" | "renew_noc" | "general_qa";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndustrialHazardBand
         * @enum {string}
         */
        IndustrialHazardBand: "G-1" | "G-2" | "G-3";
        /**
         * OccupancyBreakdownItem
         * @description One component of a mixed-occupancy building (B.4).
         *
         *     floor_area_sqm is an addition beyond the original B.4 schema: Table 7's
         *     bands are height/area-driven, so classifying a single component requires
         *     its own floor area even though the whole building shares one height_m.
         *     Optional because the union-of-clauses logic (see
         *     app/engine/classifier.py's classify_mixed_use) still degrades to "flag
         *     for human review" rather than guessing when it's missing for a component.
         */
        OccupancyBreakdownItem: {
            type: components["schemas"]["OccupancyType"];
            /** Floor Range */
            floor_range: string;
            /** Floor Area Sqm */
            floor_area_sqm?: number | null;
            /**
             * Subdivision
             * @description Same purpose as CaseFile.occupancy_subdivision, but per-component: needed when this component's occupancy type is one of the ones whose Table 7 has multiple genuinely different subdivisions (see occupancy_subdivision's docstring).
             */
            subdivision?: string | null;
        };
        /**
         * OccupancyType
         * @enum {string}
         */
        OccupancyType: "Residential" | "Educational" | "Institutional" | "Assembly" | "Business" | "Mercantile" | "Industrial" | "Storage" | "Hazardous" | "Mixed Use";
        /**
         * ProjectStage
         * @enum {string}
         */
        ProjectStage: "concept" | "plan_submitted" | "under_construction" | "renewal";
        /** SourceDocument */
        SourceDocument: {
            /** Filename */
            filename: string;
            /**
             * Pages
             * @default 0
             */
            pages: number;
            /**
             * Extraction Tier Used
             * @description 1-5, see B.7 tiered OCR pipeline
             */
            extraction_tier_used?: number | null;
            /**
             * Overall Confidence
             * @default 0
             */
            overall_confidence: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_case_file_case_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CaseFile"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_file_case_files__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_file_case_files__session_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_case_file_case_files__session_id__classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_case_files__session_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_case_files__session_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_case_files__session_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_case_files__session_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_case_files__session_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
