/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/case-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case File */
        post: operations["create_case_file_case_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/opening-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opening Message
         * @description The greeting + first intake question for a not-yet-created case file.
         *
         *     Exists so the Overview page can show the assistant's opening message
         *     immediately WITHOUT creating (and therefore persisting) a case file.
         *     Before this, merely opening the Overview page created a project - so
         *     navigating away and back repeatedly littered Project History with
         *     empty projects the user never actually started. A case file is now
         *     only created once there's something real to record: a typed answer or
         *     an uploaded document. Persists nothing; `start_conversation` here runs
         *     against a throwaway in-memory CaseFile purely to render the prompt.
         */
        get: operations["get_opening_message_case_files_opening_message_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case File */
        get: operations["get_case_file_case_files__session_id__get"];
        /** Update Case File */
        put: operations["update_case_file_case_files__session_id__put"];
        post?: never;
        /**
         * Delete Case File
         * @description Deletes a project: the case file AND its whole chat transcript.
         *
         *     Both, explicitly - a user deleting a project expects their conversation
         *     to go with it, not to be left behind in the database. Irreversible;
         *     there is no soft-delete/undo, so the UI confirms first.
         */
        delete: operations["delete_case_file_case_files__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Case File
         * @description Attaches an anonymous case file to the calling account.
         *
         *     Closes a real gap in Phase 2's account model: `owner_user_id` was only
         *     ever set at creation time, so a project someone started before signing
         *     in stayed anonymous forever - invisible in Project History and in the
         *     chat rail, even to the person who had just created it in that same
         *     browser. Claiming is the one operation that may set an owner after the
         *     fact.
         *
         *     Only an UNOWNED case file can be claimed. Claiming one you already own
         *     is a no-op (idempotent, so a retry or React's double-invoked effect is
         *     harmless); claiming someone else's is a 403, exactly like every other
         *     access to it - this must never become a way to take over a project by
         *     guessing a session id.
         */
        post: operations["claim_case_file_case_files__session_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Case File */
        post: operations["classify_case_file_case_files__session_id__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What If Case File
         * @description Phase 2: "what if this field were X" - reclassifies a hypothetical
         *     copy of the case file so the UI can show the resulting classification/
         *     compliance without ever touching the real one. Same merge-and-
         *     revalidate `update_case_file` above uses, then the same `classify()`
         *     real classification uses - deliberately no separate what-if business
         *     logic to keep in sync with the real rules - but this never calls
         *     store_save(), so the persisted case file (and its conversation_stage)
         *     is completely unaffected by exploring a scenario.
         */
        post: operations["what_if_case_file_case_files__session_id__what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_case_files__session_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Pdf
         * @description Phase 2: a real PDF of the same report /report already returns as
         *     markdown - never a second source of truth for report content, see
         *     app/reports/exporters.py.
         */
        get: operations["get_report_pdf_case_files__session_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/report.docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Docx
         * @description Phase 2: a real DOCX counterpart to /report.pdf above.
         */
        get: operations["get_report_docx_case_files__session_id__report_docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Returns the opening question (product scope B.5, Node 0/1) without
         *     consuming a user message - call this once right after creating a case
         *     file to get the first prompt to show the user.
         */
        post: operations["start_case_files__session_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description The persisted chat transcript, oldest-first - what the Overview page
         *     reloads so leaving the page (or reopening the project later from
         *     Project History) doesn't lose the conversation. Returns the most recent
         *     `limit` messages; page further back with `before_id` (the id of the
         *     oldest message already held).
         */
        get: operations["get_messages_case_files__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Changes
         * @description The per-field change log for one case file, NEWEST first.
         *
         *     The answer to "this building was 24 m yesterday and 68 m today - who
         *     changed it, and off the back of what?", which Project History (a
         *     project list showing only current state) could never give. Returns the
         *     most recent `limit` changes; page further back with `before_id`.
         */
        get: operations["get_changes_case_files__session_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_case_files__session_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/case-files/{session_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Product scope §B.7 - runs the tiered OCR/vision pipeline on an
         *     uploaded PDF/PNG/JPEG, extracts whatever Case File facts it can, and
         *     merges them in as document-sourced (never higher-confidence than a
         *     user's own chat answer - see app/ingest/apply.py). Every field this
         *     finds still needs the same B.5 Node 8 confirmation as any other
         *     document-sourced fact before a report is generated - this endpoint pre-
         *     fills, it never finalizes.
         */
        post: operations["upload_document_case_files__session_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/case-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Case Files
         * @description Phase 2's starting point for Project History (§ "Project history"):
         *     every case file this account owns, newest-updated first.
         */
        get: operations["list_my_case_files_users_me_case_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["User"];
        };
        /** Body_upload_document_case_files__session_id__documents_post */
        Body_upload_document_case_files__session_id__documents_post: {
            /** File */
            file: string;
        };
        /** CaseFile */
        CaseFile: {
            /** Session Id */
            session_id: string;
            /**
             * Owner User Id
             * @description Phase 2: the account this case file belongs to, if any. None means an anonymous case file (Phase 1's original model - the session_id itself is the only access control, same as before). When set, only that account may access this case file - see app/api/case_files.py's _check_access().
             */
            owner_user_id?: string | null;
            /**
             * Project Name
             * @default
             */
            project_name: string;
            /**
             * State
             * @default
             */
            state: string;
            /**
             * City
             * @default
             */
            city: string;
            occupancy_type?: components["schemas"]["OccupancyType"] | null;
            /**
             * Occupancy Subdivision
             * @description NBCS subdivision code where Table 7's bands genuinely differ by subdivision (e.g. 'A-I' lodging house vs 'A-V' starred hotel within Residential; 'C-I' hospitals vs 'C-II_C-III' custodial/penal within Institutional; 'E-I'/'E-II' human-occupied vs datacentre within Business; 'F'/'F-II' vs underground shopping within Mercantile). NOT part of the original B.4 schema in the product scope document - added because the classifier cannot safely pick a Table 7 band without it for these occupancies. Industrial does not need this field; use industrial_hazard_band.
             */
            occupancy_subdivision?: string | null;
            industrial_hazard_band?: components["schemas"]["IndustrialHazardBand"] | null;
            /**
             * Mixed Occupancy
             * @default false
             */
            mixed_occupancy: boolean;
            /** Occupancy Breakdown */
            occupancy_breakdown?: components["schemas"]["OccupancyBreakdownItem"][];
            /** Height M */
            height_m?: number | null;
            /** Is High Rise */
            is_high_rise?: boolean | null;
            /** Floors Above Ground */
            floors_above_ground?: number | null;
            /** Floors Below Ground */
            floors_below_ground?: number | null;
            /** Built Up Area Sqm */
            built_up_area_sqm?: number | null;
            /** Floor Wise Area */
            floor_wise_area?: components["schemas"]["FloorAreaItem"][];
            /** Number Of Staircases */
            number_of_staircases?: number | null;
            /** Number Of Exits */
            number_of_exits?: number | null;
            /** Existing Fire Systems */
            existing_fire_systems?: string[];
            /**
             * Kitchen Count
             * @description Additions beyond the original B.4 schema, alongside door_count. Report-facing/informational only, same as floor_wise_area - no digitized NBCS Table 7 lookup currently keys off kitchen presence or door count, so these never feed classify().
             */
            kitchen_count?: number | null;
            /** Door Count */
            door_count?: number | null;
            project_stage?: components["schemas"]["ProjectStage"] | null;
            goal?: components["schemas"]["Goal"] | null;
            /**
             * @description Which code edition governs this case. Defaults to 2026 (the live/primary source) unless the case involves a building certified under 2016 and not yet reassessed.
             * @default 2026
             */
            code_edition: components["schemas"]["CodeEdition"];
            /** Source Documents */
            source_documents?: components["schemas"]["SourceDocument"][];
            /** Field Sources */
            field_sources?: {
                [key: string]: components["schemas"]["FieldSource"];
            };
            classification_result?: components["schemas"]["ClassificationResult"];
            /** @default intake */
            conversation_stage: components["schemas"]["ConversationStage"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * ChangeSource
         * @description Where a change came from. Mirrors the provenance vocabulary the Case
         *     File already uses for `field_sources`, plus the two ways a value can be
         *     set without a person typing it.
         * @enum {string}
         */
        ChangeSource: "user" | "dialogue" | "document" | "system";
        /** ClassificationResult */
        ClassificationResult: {
            /** Applies */
            applies?: boolean | null;
            /**
             * Table 7 Ref
             * @default
             */
            table_7_ref: string;
            /** Applicable Clauses */
            applicable_clauses?: string[];
            /** Applicable State Checklist Id */
            applicable_state_checklist_id?: string | null;
            /** Is High Rise */
            is_high_rise?: boolean | null;
            /**
             * Require Human Review Flag
             * @default false
             */
            require_human_review_flag: boolean;
            /**
             * Protection Level
             * @description e.g. 'HL-3' or 'CL-4' from Table 7A-7J
             */
            protection_level?: string | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * CodeEdition
         * @enum {string}
         */
        CodeEdition: "2026" | "2016";
        /** ConversationMessage */
        ConversationMessage: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: string;
            role: components["schemas"]["MessageRole"];
            /** @default text */
            kind: components["schemas"]["MessageKind"];
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Payload
             * @description Structured data for a non-text kind: the IngestSummary for a document_result, the ClassificationResult for a classification_result. None for plain text messages.
             */
            payload?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ConversationStage
         * @enum {string}
         */
        ConversationStage: "intake" | "confirming" | "classified" | "report_ready";
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** FieldChange */
        FieldChange: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: string;
            /** Field */
            field: string;
            /**
             * Old Value
             * @description The JSON value before the change. None for a field that had no value.
             */
            old_value?: unknown | null;
            /**
             * New Value
             * @description The JSON value after the change. None if the field was cleared.
             */
            new_value?: unknown | null;
            source: components["schemas"]["ChangeSource"];
            /**
             * Actor User Id
             * @description The account that caused the change, when there was one. None for an anonymous session.
             */
            actor_user_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FieldSource */
        FieldSource: {
            /** Value */
            value?: unknown;
            /** @default unknown */
            source: components["schemas"]["FieldSourceKind"];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /**
         * FieldSourceKind
         * @enum {string}
         */
        FieldSourceKind: "user" | "document" | "inferred" | "unknown";
        /**
         * FloorAreaItem
         * @description One row of a floor-wise area breakdown - an addition beyond the
         *     original B.4 schema (which only has a single built_up_area_sqm total).
         *     Added because architectural drawings' "area statement" schedules give
         *     area per floor, not just a building total, and that's useful to capture
         *     even though today's digitized NBCS Table 7 lookups still key off the
         *     single built_up_area_sqm total (see classifier.py) - this is
         *     informational/report-facing only, not a classification input, per an
         *     explicit product decision to not invent NBCS clause logic that doesn't
         *     exist in the digitized rule data.
         */
        FloorAreaItem: {
            /** Floor */
            floor: string;
            /** Area Sqm */
            area_sqm: number;
        };
        /**
         * Goal
         * @enum {string}
         */
        Goal: "understand_requirements" | "prep_noc" | "renew_noc" | "general_qa";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndustrialHazardBand
         * @enum {string}
         */
        IndustrialHazardBand: "G-1" | "G-2" | "G-3";
        /**
         * MessageKind
         * @description How the frontend should render this message - mirrors the
         *     ConversationEntry union in frontend/src/pages/overview/conversation.ts.
         *     Stored rather than re-derived so a reloaded transcript renders exactly
         *     as it did live (a document result as its result card, a classification
         *     as its summary card), instead of collapsing to undifferentiated text.
         * @enum {string}
         */
        MessageKind: "text" | "document_result" | "classification_result";
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "agent" | "system";
        /**
         * OccupancyBreakdownItem
         * @description One component of a mixed-occupancy building (B.4).
         *
         *     floor_area_sqm is an addition beyond the original B.4 schema: Table 7's
         *     bands are height/area-driven, so classifying a single component requires
         *     its own floor area even though the whole building shares one height_m.
         *     Optional because the union-of-clauses logic (see
         *     app/engine/classifier.py's classify_mixed_use) still degrades to "flag
         *     for human review" rather than guessing when it's missing for a component.
         */
        OccupancyBreakdownItem: {
            type: components["schemas"]["OccupancyType"];
            /** Floor Range */
            floor_range: string;
            /** Floor Area Sqm */
            floor_area_sqm?: number | null;
            /**
             * Subdivision
             * @description Same purpose as CaseFile.occupancy_subdivision, but per-component: needed when this component's occupancy type is one of the ones whose Table 7 has multiple genuinely different subdivisions (see occupancy_subdivision's docstring).
             */
            subdivision?: string | null;
        };
        /**
         * OccupancyType
         * @enum {string}
         */
        OccupancyType: "Residential" | "Educational" | "Institutional" | "Assembly" | "Business" | "Mercantile" | "Industrial" | "Storage" | "Hazardous" | "Mixed Use";
        /**
         * ProjectStage
         * @enum {string}
         */
        ProjectStage: "concept" | "plan_submitted" | "under_construction" | "renewal";
        /** SourceDocument */
        SourceDocument: {
            /** Filename */
            filename: string;
            /**
             * Pages
             * @default 0
             */
            pages: number;
            /**
             * Extraction Tier Used
             * @description 1-5, see B.7 tiered OCR pipeline
             */
            extraction_tier_used?: number | null;
            /**
             * Overall Confidence
             * @default 0
             */
            overall_confidence: number;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_case_file_case_files_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CaseFile"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opening_message_case_files_opening_message_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_case_file_case_files__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_file_case_files__session_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_file_case_files__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_case_file_case_files__session_id__claim_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_case_file_case_files__session_id__classify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_case_file_case_files__session_id__what_if_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_case_files__session_id__report_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_pdf_case_files__session_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_docx_case_files__session_id__report_docx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_case_files__session_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_case_files__session_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_changes_case_files__session_id__changes_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_case_files__session_id__message_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_case_files__session_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_case_files__session_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_case_files_users_me_case_files_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
