"""Baseline: the schema as it stood when Alembic was adopted.

Not a change - a starting point. Every table here was created by
`Base.metadata.create_all()` before this project had migrations, so this
revision exists to give those databases a version to be AT, and to give a
brand-new database one command that builds the whole schema.

A database that predates Alembic is brought to this point and stamped
rather than re-created - see app/db/init_db.py::run_migrations, which is
where the adoption path is implemented and explained.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-14
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Creates every table. Autogenerated from the models, then read
    through line by line against app/db/models.py."""
    op.create_table('case_file_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_file_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_changes_session_id'), ['session_id'], unique=False)

    op.create_table('case_file_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('granted_to_user_id', sa.String(), nullable=False),
    sa.Column('granted_to_email', sa.String(), nullable=False),
    sa.Column('granted_by_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'granted_to_user_id', name='uq_case_file_grant')
    )
    with op.batch_alter_table('case_file_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_grants_granted_to_user_id'), ['granted_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_grants_session_id'), ['session_id'], unique=False)

    op.create_table('case_file_invites',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('invited_email', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('case_file_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_invites_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_file_invites_session_id'), ['session_id'], unique=False)

    op.create_table('case_file_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_file_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_file_reviews_session_id'), ['session_id'], unique=False)

    op.create_table('case_files',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_files_requires_review'), ['requires_review'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_session_id'), ['session_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)



def downgrade() -> None:
    """Drops every table - i.e. the entire database. Kept because a
    baseline with no downgrade breaks `alembic downgrade base` in a test,
    not because anyone should run it against real data."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_expires_at'))

    op.drop_table('password_resets')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_session_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_requires_review'))
        batch_op.drop_index(batch_op.f('ix_case_files_owner_user_id'))

    op.drop_table('case_files')
    with op.batch_alter_table('case_file_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_reviews_session_id'))

    op.drop_table('case_file_reviews')
    with op.batch_alter_table('case_file_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_invites_session_id'))
        batch_op.drop_index(batch_op.f('ix_case_file_invites_expires_at'))

    op.drop_table('case_file_invites')
    with op.batch_alter_table('case_file_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_grants_session_id'))
        batch_op.drop_index(batch_op.f('ix_case_file_grants_granted_to_user_id'))

    op.drop_table('case_file_grants')
    with op.batch_alter_table('case_file_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_file_changes_session_id'))

    op.drop_table('case_file_changes')
